# -*- coding: utf-8 -*-
"""Copy of Cyber Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkJhMV3A2D4Sg35ACjC6dfCuvfJl095O
"""

import numpy as np
import cv2
import zlib
import math
import os
from tqdm import tqdm


def get_video_chunks(file_path, chunk_size=8, max_frames=None):
    """
    Generator that yields 4D color chunks (F, H, W, 3).
    Ensures dimensions are even by trimming (no padding).
    """
    cap = cv2.VideoCapture(file_path)
    total_count = 0

    while True:
        chunk = []
        for _ in range(chunk_size):
            if max_frames and total_count >= max_frames:
                break
            ret, frame = cap.read()
            if not ret:
                break

            h, w, _ = frame.shape


            frame = frame[:h - (h % 2), :w - (w % 2), :]

            chunk.append(frame)
            total_count += 1

        if not chunk:
            break


        if len(chunk) % 2 != 0:
            chunk.pop()

        if not chunk:
            break

        yield np.array(chunk, dtype=np.uint8)

    cap.release()


def compress_video(video_array):
    raw_data = video_array.tobytes()
    compressed = zlib.compress(raw_data, level=9)
    return np.unpackbits(np.frombuffer(compressed, dtype=np.uint8))


def decompress_video(bits, shape):
    byte_data = np.packbits(bits).tobytes()
    decompressed = zlib.decompress(byte_data)
    return np.frombuffer(decompressed, dtype=np.uint8).reshape(shape)

def lwt_1d(data):
    data = data.astype(np.int32)
    evens, odds = data[0::2], data[1::2]
    d = odds - evens
    s = evens + (d // 2)
    return np.concatenate([s, d])

def ilwt_1d(data):
    half = data.shape[0] // 2
    s, d = data[:half], data[half:]
    evens = s - (d // 2)
    odds = d + evens
    recon = np.empty_like(data)
    recon[0::2], recon[1::2] = evens, odds
    return recon


def transform_3d_chunk(volume, forward=True):
    """Now supports both grayscale (F,H,W) and color (F,H,W,3)"""

    func = lwt_1d if forward else ilwt_1d


    if volume.ndim == 3:
        out = volume.copy().astype(np.int32)

        for y in range(out.shape[1]):
            for x in range(out.shape[2]):
                out[:, y, x] = func(out[:, y, x])

        for f in range(out.shape[0]):
            for x in range(out.shape[2]):
                out[f, :, x] = func(out[f, :, x])

        for f in range(out.shape[0]):
            for y in range(out.shape[1]):
                out[f, y, :] = func(out[f, y, :])

        return out


    elif volume.ndim == 4:
        F, H, W, C = volume.shape
        out = np.zeros_like(volume, dtype=np.int32)

        for c in range(C):
            channel = volume[:, :, :, c].astype(np.int32)

            for y in range(H):
                for x in range(W):
                    channel[:, y, x] = func(channel[:, y, x])

            for f in range(F):
                for x in range(W):
                    channel[f, :, x] = func(channel[f, :, x])

            for f in range(F):
                for y in range(H):
                    channel[f, y, :] = func(channel[f, y, :])

            out[:, :, :, c] = channel

        return out

import numpy as np
import cv2
import zlib
from tqdm import tqdm

def run_steganography_pipeline(cover_path, secret_path, stego_path, recovered_path, chunk_size=8):

    cap_s = cv2.VideoCapture(secret_path)
    s_frames = []
    for _ in range(30):
        ret, f = cap_s.read()
        if not ret: break

        h, w, _ = f.shape
        f = f[:h-(h%2), :w-(w%2), :]

        s_frames.append(f)

    cap_s.release()

    secret_vid = np.array(s_frames, dtype=np.uint8)

    if len(secret_vid) % 2 != 0:
        secret_vid = secret_vid[:-1]

    secret_shape = secret_vid.shape


    compressed_bytes = secret_vid.tobytes()
    secret_bits = np.unpackbits(np.frombuffer(compressed_bytes, dtype=np.uint8))
    bit_len = len(secret_bits)


    bits_per_chunk_tracker = []
    bit_ptr = 0
    CHUNK_SIZE = chunk_size

    cap_c = cv2.VideoCapture(cover_path)
    total_f = int(cap_c.get(cv2.CAP_PROP_FRAME_COUNT))
    cap_c.release()
    total_chunks = total_f // CHUNK_SIZE

    print(f"Embedding {bit_len} bits into {total_chunks} chunks...")

    writer = None
    first_write = True

    for cover_chunk in tqdm(get_video_chunks(cover_path, CHUNK_SIZE), total=total_chunks, desc="Embedding"):

        cover_chunk = np.clip(cover_chunk, 5, 250).astype(np.uint8)


        coeffs = transform_3d_chunk(cover_chunk, forward=True)

        flat = coeffs.flatten()

        chunk_cap = int(len(flat) * 0.85)
        bits_to_hide = min(bit_len - bit_ptr, chunk_cap)
        bits_per_chunk_tracker.append(bits_to_hide)

        if bits_to_hide > 0:
            segment = secret_bits[bit_ptr : bit_ptr + bits_to_hide]
            flat[-bits_to_hide:] = (flat[-bits_to_hide:] & ~1) | segment
            bit_ptr += bits_to_hide

        stego_coeffs = flat.reshape(coeffs.shape)

        stego_chunk = transform_3d_chunk(stego_coeffs, forward=False)
        stego_chunk = np.clip(stego_chunk, 0, 255).astype(np.uint8)

        if first_write:
            f, h, w, c = stego_chunk.shape
            writer = cv2.VideoWriter(stego_path, cv2.VideoWriter_fourcc(*'FFV1'), 30, (w, h), True)  # ✅ COLOR
            first_write = False

        for frame in stego_chunk:
            writer.write(frame)

    writer.release()


    print("\n--- Starting Extraction ---")

    extracted_bits_list = []
    bits_left_to_extract = bit_len

    chunk_gen = get_video_chunks(stego_path, CHUNK_SIZE)

    for i, stego_chunk in enumerate(tqdm(chunk_gen, desc="Extracting")):

        coeffs = transform_3d_chunk(stego_chunk, forward=True)
        flat = coeffs.flatten()

        chunk_cap = int(len(flat) * 0.85)
        bits_to_pull = min(bits_left_to_extract, chunk_cap)

        if bits_to_pull > 0:
            segment = flat[-bits_to_pull:] & 1
            extracted_bits_list.append(segment)
            bits_left_to_extract -= bits_to_pull

        if bits_left_to_extract <= 0:
            break

    if bits_left_to_extract > 0:
        print(f"CRITICAL ERROR: Missing {bits_left_to_extract} bits.")
        return

    full_extracted_bits = np.concatenate(extracted_bits_list)[:bit_len]
    recovered_bytes = np.packbits(full_extracted_bits)


    recovered_vid = recovered_bytes.reshape(secret_shape)


    f_s, h_s, w_s, c_s = recovered_vid.shape
    rec_writer = cv2.VideoWriter(recovered_path, cv2.VideoWriter_fourcc(*'FFV1'), 30, (w_s, h_s), True)

    for frame in recovered_vid:
        rec_writer.write(frame.astype(np.uint8))

    rec_writer.release()

    print(f"Success! Saved to {recovered_path}")

COVER_PATH = "/content/cover.y4m"
SECRET_PATH = "/content/secret.y4m"
STEGO_OUTPUT = "stego_video.mkv"
RECOVERED_OUTPUT = "recovered_secret.mkv"
CHUNK_SIZE = 32

run_steganography_pipeline(COVER_PATH, SECRET_PATH, STEGO_OUTPUT, RECOVERED_OUTPUT, CHUNK_SIZE)